[server]
# port = 8080
# env = "development"
# pepper = "random string for password hashing"

[server.limiter]
# enabled = true
# rps = 2.0
# burst = 4

[server.tokens]
# activationTokenTTL = "10m"
# passwordResetTokenTTL = "10m"
# accessTokenTTL = "1h"
# refreshTokenTTL = "24h"

[database]
# dsn = "postgres://username:password@host:port/db?sslmode=disable"
# maxOpenConns = 25
# maxIdleConns = 25
# maxIdleTime = 15m

[mailer]
# sender = "Yatijapp <no-reply@yatijapp.fakemail.com>"

[mailer.smtp]
# host = "sandbox.smtp.mailtrap.io"
# port = 25
# username = ""
# password = ""
 
